spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/uniflow_db
    username: postgres
    password: Walex@2020
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true