# ============================================
# SERVER CONFIGURATION
# ============================================
server.port=8081
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.bpdcpjwwqkteqpqxiusz
spring.datasource.password=Ln8zz1m58kRxpFFD
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# Disable Flyway
spring.flyway.enabled=false

app.jwt.secret=0BKdpP/yW0b0BG5tzWOkBeXNcnksnD/KC852SuQ96rSJIBtCt1Op/Y17HqGfGAEc
app.jwt.expiration.ms=86400000

# 💡 Note: If your Vite frontend runs on port 5173, change 3000 to 5173 here
app.cors.allowed-origins=https://uniflow-queue-system-1.onrender.com,http://localhost:3000
app.frontend.url=https://uniflow-queue-system-1.onrender.com


spring.mail.host=://gmail.com
spring.mail.port=587
spring.mail.username=uniflow925@gmail.com
spring.mail.password=zumr jdtd qllc hbku
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ============================================
# LOGGING CONFIGURATION
# ============================================
logging.level.org.springframework.mail=DEBUG
logging.level.com.uniflow=DEBUG

# src/main/resources/application.properties
supabase.service.role.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwZGNwand3cWt0ZXFwcXhpdXN6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4ODc5NjcyMCwiZXhwIjoyMTA0MzcyNzIwfQ.mya_UAUrK3ueXz14jingkLj97ZLplwpYzWvX95UUcAw