spring:
  datasource:
    url: ${jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require}
    username: ${postgres.bpdcpjwwqkteqpqxiusz}
    password: ${pJoi4lextcPdkv2C}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false